on:
  workflow_dispatch:
    inputs:
      version:
        description: "Neue API Version erstellen (z.B. 1.8-rc1)"
        required: true
        default: ""
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    name: Bereitet die Umgebung vor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '1'
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
  create-new-version:
    name: Erstellt neue Versionsdokumentation
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
      - name: config git
        run: |
          git config user.name "gh-action[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Create new Version
        run: npm run docusaurus docs:version ${{ inputs.version }}
      - name: create branch and push
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH="version/${{ inputs.version }}-autogenerated
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "chore: auto generate version ${{ inputs.version }}"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push -u origin "$BRANCH"
      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
           --base main \
           --head "$BRANCH" \
           --title "chore: Automatisch Generierte Version ${{ inputs.version }} \
           --body "Dieser PR wurde automatisiert erstellt."