on:
  workflow_dispatch:
    inputs:
      version:
        description: "Neue API Version erstellen (z.B. v1.8)"
        required: true
        default: ""
        type: string

jobs:
  prepare:
    name: Bereitet die Umgebung vor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '1'
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
  create-version:
    name: Erstellt neue API Version
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Create new Version
        run: npm run docusaurus docs:version ${{ inputs.version }}
  create-pr:
    name: Erstellt einen automatisierten Pull Request
    runs-on: ubuntu-latest
    needs: create-version
    steps:
      - name: Log new version
        run: echo ${{ inputs.version }}